services:
  mysql:
    image: mysql:8.0
    container_name: ai_document_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: ai_document_redis
    restart: always


  backend:
    build: .
    container_name: ai_document_backend
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379
      FILE_UPLOAD_DIR: uploads

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_HOST: ${PINECONE_INDEX_HOST}
      PINECONE_NAMESPACE: ${PINECONE_NAMESPACE}

      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    container_name: ai_document_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data:
  uploads_data: