package com.abhay.aidocument.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String apiKey;

    private final RestClient restClient = RestClient.create();

    public String askQuestion(String documentText, String question) {

        String prompt = """
                Answer the user's question using ONLY the uploaded document.

                If answer is not present, say:
                I could not find this information in the uploaded file.

                Document:
                %s

                Question:
                %s
                """.formatted(documentText, question);

        return callGemini(prompt);
    }

    public String askQuestionWithContext(String context, String question) {

        String prompt = """
                Answer the user's question using ONLY this relevant context.

                If the answer is not present, say:
                I could not find this information in the uploaded file.

                Relevant Context:
                %s

                Question:
                %s
                """.formatted(context, question);

        return callGemini(prompt);
    }

    public String summarize(String documentText) {

        String prompt = """
                Summarize this document clearly in bullet points:

                %s
                """.formatted(documentText);

        return callGemini(prompt);
    }

    private String callGemini(String prompt) {

        String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + apiKey;

        Map<String, Object> requestBody = Map.of(
                "contents", List.of(
                        Map.of(
                                "parts", List.of(
                                        Map.of("text", prompt)
                                )
                        )
                )
        );

        Map response = restClient.post()
                .uri(url)
                .header("Content-Type", "application/json")
                .body(requestBody)
                .retrieve()
                .body(Map.class);

        List candidates = (List) response.get("candidates");

        if (candidates == null || candidates.isEmpty()) {
            return "No response generated by AI.";
        }

        Map firstCandidate = (Map) candidates.get(0);
        Map content = (Map) firstCandidate.get("content");
        List parts = (List) content.get("parts");

        if (parts == null || parts.isEmpty()) {
            return "No response generated by AI.";
        }

        Map firstPart = (Map) parts.get(0);

        return firstPart.get("text").toString();
    }
}